// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/skillcoder/preoomkiller-controller/internal/logic/controller"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRepository creates a new instance of MockRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRepository {
	mock := &MockRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRepository is an autogenerated mock type for the Repository type
type MockRepository struct {
	mock.Mock
}

type MockRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRepository) EXPECT() *MockRepository_Expecter {
	return &MockRepository_Expecter{mock: &_m.Mock}
}

// EvictPodCommand provides a mock function for the type MockRepository
func (_mock *MockRepository) EvictPodCommand(ctx context.Context, namespace string, name string) error {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for EvictPodCommand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_EvictPodCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EvictPodCommand'
type MockRepository_EvictPodCommand_Call struct {
	*mock.Call
}

// EvictPodCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockRepository_Expecter) EvictPodCommand(ctx interface{}, namespace interface{}, name interface{}) *MockRepository_EvictPodCommand_Call {
	return &MockRepository_EvictPodCommand_Call{Call: _e.mock.On("EvictPodCommand", ctx, namespace, name)}
}

func (_c *MockRepository_EvictPodCommand_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockRepository_EvictPodCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_EvictPodCommand_Call) Return(err error) *MockRepository_EvictPodCommand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_EvictPodCommand_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) error) *MockRepository_EvictPodCommand_Call {
	_c.Call.Return(run)
	return _c
}

// GetPodMetricsQuery provides a mock function for the type MockRepository
func (_mock *MockRepository) GetPodMetricsQuery(ctx context.Context, namespace string, name string) (*controller.PodMetrics, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetPodMetricsQuery")
	}

	var r0 *controller.PodMetrics
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (*controller.PodMetrics, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) *controller.PodMetrics); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*controller.PodMetrics)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetPodMetricsQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPodMetricsQuery'
type MockRepository_GetPodMetricsQuery_Call struct {
	*mock.Call
}

// GetPodMetricsQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockRepository_Expecter) GetPodMetricsQuery(ctx interface{}, namespace interface{}, name interface{}) *MockRepository_GetPodMetricsQuery_Call {
	return &MockRepository_GetPodMetricsQuery_Call{Call: _e.mock.On("GetPodMetricsQuery", ctx, namespace, name)}
}

func (_c *MockRepository_GetPodMetricsQuery_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockRepository_GetPodMetricsQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetPodMetricsQuery_Call) Return(podMetrics *controller.PodMetrics, err error) *MockRepository_GetPodMetricsQuery_Call {
	_c.Call.Return(podMetrics, err)
	return _c
}

func (_c *MockRepository_GetPodMetricsQuery_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) (*controller.PodMetrics, error)) *MockRepository_GetPodMetricsQuery_Call {
	_c.Call.Return(run)
	return _c
}

// GetPodQuery provides a mock function for the type MockRepository
func (_mock *MockRepository) GetPodQuery(ctx context.Context, namespace string, name string) (controller.Pod, error) {
	ret := _mock.Called(ctx, namespace, name)

	if len(ret) == 0 {
		panic("no return value specified for GetPodQuery")
	}

	var r0 controller.Pod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (controller.Pod, error)); ok {
		return returnFunc(ctx, namespace, name)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) controller.Pod); ok {
		r0 = returnFunc(ctx, namespace, name)
	} else {
		r0 = ret.Get(0).(controller.Pod)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, namespace, name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_GetPodQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPodQuery'
type MockRepository_GetPodQuery_Call struct {
	*mock.Call
}

// GetPodQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
func (_e *MockRepository_Expecter) GetPodQuery(ctx interface{}, namespace interface{}, name interface{}) *MockRepository_GetPodQuery_Call {
	return &MockRepository_GetPodQuery_Call{Call: _e.mock.On("GetPodQuery", ctx, namespace, name)}
}

func (_c *MockRepository_GetPodQuery_Call) Run(run func(ctx context.Context, namespace string, name string)) *MockRepository_GetPodQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockRepository_GetPodQuery_Call) Return(pod controller.Pod, err error) *MockRepository_GetPodQuery_Call {
	_c.Call.Return(pod, err)
	return _c
}

func (_c *MockRepository_GetPodQuery_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string) (controller.Pod, error)) *MockRepository_GetPodQuery_Call {
	_c.Call.Return(run)
	return _c
}

// ListPodsQuery provides a mock function for the type MockRepository
func (_mock *MockRepository) ListPodsQuery(ctx context.Context, labelSelector string) ([]controller.Pod, error) {
	ret := _mock.Called(ctx, labelSelector)

	if len(ret) == 0 {
		panic("no return value specified for ListPodsQuery")
	}

	var r0 []controller.Pod
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]controller.Pod, error)); ok {
		return returnFunc(ctx, labelSelector)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []controller.Pod); ok {
		r0 = returnFunc(ctx, labelSelector)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]controller.Pod)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, labelSelector)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRepository_ListPodsQuery_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListPodsQuery'
type MockRepository_ListPodsQuery_Call struct {
	*mock.Call
}

// ListPodsQuery is a helper method to define mock.On call
//   - ctx context.Context
//   - labelSelector string
func (_e *MockRepository_Expecter) ListPodsQuery(ctx interface{}, labelSelector interface{}) *MockRepository_ListPodsQuery_Call {
	return &MockRepository_ListPodsQuery_Call{Call: _e.mock.On("ListPodsQuery", ctx, labelSelector)}
}

func (_c *MockRepository_ListPodsQuery_Call) Run(run func(ctx context.Context, labelSelector string)) *MockRepository_ListPodsQuery_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRepository_ListPodsQuery_Call) Return(pods []controller.Pod, err error) *MockRepository_ListPodsQuery_Call {
	_c.Call.Return(pods, err)
	return _c
}

func (_c *MockRepository_ListPodsQuery_Call) RunAndReturn(run func(ctx context.Context, labelSelector string) ([]controller.Pod, error)) *MockRepository_ListPodsQuery_Call {
	_c.Call.Return(run)
	return _c
}

// SetAnnotationCommand provides a mock function for the type MockRepository
func (_mock *MockRepository) SetAnnotationCommand(ctx context.Context, namespace string, name string, key string, value string) error {
	ret := _mock.Called(ctx, namespace, name, key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetAnnotationCommand")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string) error); ok {
		r0 = returnFunc(ctx, namespace, name, key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRepository_SetAnnotationCommand_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetAnnotationCommand'
type MockRepository_SetAnnotationCommand_Call struct {
	*mock.Call
}

// SetAnnotationCommand is a helper method to define mock.On call
//   - ctx context.Context
//   - namespace string
//   - name string
//   - key string
//   - value string
func (_e *MockRepository_Expecter) SetAnnotationCommand(ctx interface{}, namespace interface{}, name interface{}, key interface{}, value interface{}) *MockRepository_SetAnnotationCommand_Call {
	return &MockRepository_SetAnnotationCommand_Call{Call: _e.mock.On("SetAnnotationCommand", ctx, namespace, name, key, value)}
}

func (_c *MockRepository_SetAnnotationCommand_Call) Run(run func(ctx context.Context, namespace string, name string, key string, value string)) *MockRepository_SetAnnotationCommand_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockRepository_SetAnnotationCommand_Call) Return(err error) *MockRepository_SetAnnotationCommand_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRepository_SetAnnotationCommand_Call) RunAndReturn(run func(ctx context.Context, namespace string, name string, key string, value string) error) *MockRepository_SetAnnotationCommand_Call {
	_c.Call.Return(run)
	return _c
}
