// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockShutdowner creates a new instance of MockShutdowner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShutdowner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShutdowner {
	mock := &MockShutdowner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShutdowner is an autogenerated mock type for the Shutdowner type
type MockShutdowner struct {
	mock.Mock
}

type MockShutdowner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShutdowner) EXPECT() *MockShutdowner_Expecter {
	return &MockShutdowner_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockShutdowner
func (_mock *MockShutdowner) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockShutdowner_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockShutdowner_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockShutdowner_Expecter) Name() *MockShutdowner_Name_Call {
	return &MockShutdowner_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockShutdowner_Name_Call) Run(run func()) *MockShutdowner_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockShutdowner_Name_Call) Return(s string) *MockShutdowner_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockShutdowner_Name_Call) RunAndReturn(run func() string) *MockShutdowner_Name_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockShutdowner
func (_mock *MockShutdowner) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShutdowner_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockShutdowner_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockShutdowner_Expecter) Shutdown(ctx interface{}) *MockShutdowner_Shutdown_Call {
	return &MockShutdowner_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockShutdowner_Shutdown_Call) Run(run func(ctx context.Context)) *MockShutdowner_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockShutdowner_Shutdown_Call) Return(err error) *MockShutdowner_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShutdowner_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *MockShutdowner_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
