// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package appstate

import (
	"time"

	"github.com/skillcoder/preoomkiller-controller/internal/infra/pinger"
	mock "github.com/stretchr/testify/mock"
)

// newMockhealthChecker creates a new instance of mockhealthChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockhealthChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockhealthChecker {
	mock := &mockhealthChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockhealthChecker is an autogenerated mock type for the healthChecker type
type mockhealthChecker struct {
	mock.Mock
}

type mockhealthChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockhealthChecker) EXPECT() *mockhealthChecker_Expecter {
	return &mockhealthChecker_Expecter{mock: &_m.Mock}
}

// GetAllStats provides a mock function for the type mockhealthChecker
func (_mock *mockhealthChecker) GetAllStats() map[string]*pinger.Statistics {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllStats")
	}

	var r0 map[string]*pinger.Statistics
	if returnFunc, ok := ret.Get(0).(func() map[string]*pinger.Statistics); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*pinger.Statistics)
		}
	}
	return r0
}

// mockhealthChecker_GetAllStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllStats'
type mockhealthChecker_GetAllStats_Call struct {
	*mock.Call
}

// GetAllStats is a helper method to define mock.On call
func (_e *mockhealthChecker_Expecter) GetAllStats() *mockhealthChecker_GetAllStats_Call {
	return &mockhealthChecker_GetAllStats_Call{Call: _e.mock.On("GetAllStats")}
}

func (_c *mockhealthChecker_GetAllStats_Call) Run(run func()) *mockhealthChecker_GetAllStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockhealthChecker_GetAllStats_Call) Return(stringToStatistics map[string]*pinger.Statistics) *mockhealthChecker_GetAllStats_Call {
	_c.Call.Return(stringToStatistics)
	return _c
}

func (_c *mockhealthChecker_GetAllStats_Call) RunAndReturn(run func() map[string]*pinger.Statistics) *mockhealthChecker_GetAllStats_Call {
	_c.Call.Return(run)
	return _c
}

// IsHealthy provides a mock function for the type mockhealthChecker
func (_mock *mockhealthChecker) IsHealthy() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsHealthy")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockhealthChecker_IsHealthy_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsHealthy'
type mockhealthChecker_IsHealthy_Call struct {
	*mock.Call
}

// IsHealthy is a helper method to define mock.On call
func (_e *mockhealthChecker_Expecter) IsHealthy() *mockhealthChecker_IsHealthy_Call {
	return &mockhealthChecker_IsHealthy_Call{Call: _e.mock.On("IsHealthy")}
}

func (_c *mockhealthChecker_IsHealthy_Call) Run(run func()) *mockhealthChecker_IsHealthy_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockhealthChecker_IsHealthy_Call) Return(b bool) *mockhealthChecker_IsHealthy_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockhealthChecker_IsHealthy_Call) RunAndReturn(run func() bool) *mockhealthChecker_IsHealthy_Call {
	_c.Call.Return(run)
	return _c
}

// newMockreadyChecker creates a new instance of mockreadyChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockreadyChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockreadyChecker {
	mock := &mockreadyChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockreadyChecker is an autogenerated mock type for the readyChecker type
type mockreadyChecker struct {
	mock.Mock
}

type mockreadyChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *mockreadyChecker) EXPECT() *mockreadyChecker_Expecter {
	return &mockreadyChecker_Expecter{mock: &_m.Mock}
}

// GetAllStats provides a mock function for the type mockreadyChecker
func (_mock *mockreadyChecker) GetAllStats() map[string]*pinger.Statistics {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllStats")
	}

	var r0 map[string]*pinger.Statistics
	if returnFunc, ok := ret.Get(0).(func() map[string]*pinger.Statistics); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*pinger.Statistics)
		}
	}
	return r0
}

// mockreadyChecker_GetAllStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllStats'
type mockreadyChecker_GetAllStats_Call struct {
	*mock.Call
}

// GetAllStats is a helper method to define mock.On call
func (_e *mockreadyChecker_Expecter) GetAllStats() *mockreadyChecker_GetAllStats_Call {
	return &mockreadyChecker_GetAllStats_Call{Call: _e.mock.On("GetAllStats")}
}

func (_c *mockreadyChecker_GetAllStats_Call) Run(run func()) *mockreadyChecker_GetAllStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockreadyChecker_GetAllStats_Call) Return(stringToStatistics map[string]*pinger.Statistics) *mockreadyChecker_GetAllStats_Call {
	_c.Call.Return(stringToStatistics)
	return _c
}

func (_c *mockreadyChecker_GetAllStats_Call) RunAndReturn(run func() map[string]*pinger.Statistics) *mockreadyChecker_GetAllStats_Call {
	_c.Call.Return(run)
	return _c
}

// IsReady provides a mock function for the type mockreadyChecker
func (_mock *mockreadyChecker) IsReady() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsReady")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// mockreadyChecker_IsReady_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsReady'
type mockreadyChecker_IsReady_Call struct {
	*mock.Call
}

// IsReady is a helper method to define mock.On call
func (_e *mockreadyChecker_Expecter) IsReady() *mockreadyChecker_IsReady_Call {
	return &mockreadyChecker_IsReady_Call{Call: _e.mock.On("IsReady")}
}

func (_c *mockreadyChecker_IsReady_Call) Run(run func()) *mockreadyChecker_IsReady_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockreadyChecker_IsReady_Call) Return(b bool) *mockreadyChecker_IsReady_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *mockreadyChecker_IsReady_Call) RunAndReturn(run func() bool) *mockreadyChecker_IsReady_Call {
	_c.Call.Return(run)
	return _c
}

// newMockstatusGetter creates a new instance of mockstatusGetter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstatusGetter(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstatusGetter {
	mock := &mockstatusGetter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstatusGetter is an autogenerated mock type for the statusGetter type
type mockstatusGetter struct {
	mock.Mock
}

type mockstatusGetter_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstatusGetter) EXPECT() *mockstatusGetter_Expecter {
	return &mockstatusGetter_Expecter{mock: &_m.Mock}
}

// GetAllStats provides a mock function for the type mockstatusGetter
func (_mock *mockstatusGetter) GetAllStats() map[string]*pinger.Statistics {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllStats")
	}

	var r0 map[string]*pinger.Statistics
	if returnFunc, ok := ret.Get(0).(func() map[string]*pinger.Statistics); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*pinger.Statistics)
		}
	}
	return r0
}

// mockstatusGetter_GetAllStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllStats'
type mockstatusGetter_GetAllStats_Call struct {
	*mock.Call
}

// GetAllStats is a helper method to define mock.On call
func (_e *mockstatusGetter_Expecter) GetAllStats() *mockstatusGetter_GetAllStats_Call {
	return &mockstatusGetter_GetAllStats_Call{Call: _e.mock.On("GetAllStats")}
}

func (_c *mockstatusGetter_GetAllStats_Call) Run(run func()) *mockstatusGetter_GetAllStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockstatusGetter_GetAllStats_Call) Return(stringToStatistics map[string]*pinger.Statistics) *mockstatusGetter_GetAllStats_Call {
	_c.Call.Return(stringToStatistics)
	return _c
}

func (_c *mockstatusGetter_GetAllStats_Call) RunAndReturn(run func() map[string]*pinger.Statistics) *mockstatusGetter_GetAllStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetStartTime provides a mock function for the type mockstatusGetter
func (_mock *mockstatusGetter) GetStartTime() time.Time {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetStartTime")
	}

	var r0 time.Time
	if returnFunc, ok := ret.Get(0).(func() time.Time); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Time)
	}
	return r0
}

// mockstatusGetter_GetStartTime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStartTime'
type mockstatusGetter_GetStartTime_Call struct {
	*mock.Call
}

// GetStartTime is a helper method to define mock.On call
func (_e *mockstatusGetter_Expecter) GetStartTime() *mockstatusGetter_GetStartTime_Call {
	return &mockstatusGetter_GetStartTime_Call{Call: _e.mock.On("GetStartTime")}
}

func (_c *mockstatusGetter_GetStartTime_Call) Run(run func()) *mockstatusGetter_GetStartTime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockstatusGetter_GetStartTime_Call) Return(time1 time.Time) *mockstatusGetter_GetStartTime_Call {
	_c.Call.Return(time1)
	return _c
}

func (_c *mockstatusGetter_GetStartTime_Call) RunAndReturn(run func() time.Time) *mockstatusGetter_GetStartTime_Call {
	_c.Call.Return(run)
	return _c
}

// GetState provides a mock function for the type mockstatusGetter
func (_mock *mockstatusGetter) GetState() State {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetState")
	}

	var r0 State
	if returnFunc, ok := ret.Get(0).(func() State); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(State)
	}
	return r0
}

// mockstatusGetter_GetState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetState'
type mockstatusGetter_GetState_Call struct {
	*mock.Call
}

// GetState is a helper method to define mock.On call
func (_e *mockstatusGetter_Expecter) GetState() *mockstatusGetter_GetState_Call {
	return &mockstatusGetter_GetState_Call{Call: _e.mock.On("GetState")}
}

func (_c *mockstatusGetter_GetState_Call) Run(run func()) *mockstatusGetter_GetState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockstatusGetter_GetState_Call) Return(state State) *mockstatusGetter_GetState_Call {
	_c.Call.Return(state)
	return _c
}

func (_c *mockstatusGetter_GetState_Call) RunAndReturn(run func() State) *mockstatusGetter_GetState_Call {
	_c.Call.Return(run)
	return _c
}

// GetUptime provides a mock function for the type mockstatusGetter
func (_mock *mockstatusGetter) GetUptime() time.Duration {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetUptime")
	}

	var r0 time.Duration
	if returnFunc, ok := ret.Get(0).(func() time.Duration); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(time.Duration)
	}
	return r0
}

// mockstatusGetter_GetUptime_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUptime'
type mockstatusGetter_GetUptime_Call struct {
	*mock.Call
}

// GetUptime is a helper method to define mock.On call
func (_e *mockstatusGetter_Expecter) GetUptime() *mockstatusGetter_GetUptime_Call {
	return &mockstatusGetter_GetUptime_Call{Call: _e.mock.On("GetUptime")}
}

func (_c *mockstatusGetter_GetUptime_Call) Run(run func()) *mockstatusGetter_GetUptime_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *mockstatusGetter_GetUptime_Call) Return(duration time.Duration) *mockstatusGetter_GetUptime_Call {
	_c.Call.Return(duration)
	return _c
}

func (_c *mockstatusGetter_GetUptime_Call) RunAndReturn(run func() time.Duration) *mockstatusGetter_GetUptime_Call {
	_c.Call.Return(run)
	return _c
}
